version: '2'

services:
  db:
    image: mariadb:10.3.0
    volumes:
      - db_data:/var/lib/mysql/data
    env_file:
      - app.env
    ports:
      - "3306:3306"
    networks:
      - network_1
    restart: always

  cdia-course:
    build: ./
    image: cdia-course
    depends_on:
      - db
    networks:
      - network_1
    env_file:
      - ./.env
    environment:
      - PORT=80
    ports:
      - "80:80"
      - "443:443"
    restart: always
